language: go
go:
  - 1.3
  - tip

env:
  global:
    - GOARCH=amd64
    - IMAGE_NAME=wibosa/hellogo
before_install:
  - go env && pwd
script: go get github.com/wibosa/hellogo && go test -v ./...

after_success:
#  - curl https://raw.githubusercontent.com/tsuru/push-to-docker/master/push.sh | bash
notifications:
  email:
    on_success: change
    on_failure: always
#  slack:
#    secure: QJe4k18ACRUP4CDo245vBFu1hpVlcR3JPWjT7NL/vAE/Y5KDn5pNXIREPYIx9F/f8lvjF2RrQxjApeUujRh1PPt2Q53JulvaDCfM5a5SYnk5yoqu3ynlfqU4AOTDa6kzoJ3K4M9X8JhMpOtr3+IOPbwV88FjPvwviZN4p0L/0wc=
services:
  - redis
  - docker
  - mongodb
matrix:
  allow_failures:
- go: tip
